### ISSUE TITLE
Support for authentication - Pact Provider 

### ISSUE THREAD

**Issue by cicdenova** [pactflow/terraform-provider-pact#14]
Hi there,

Thank you for opening an issue. Please modify the below as required to help raise an issue or request a feature.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
v0.14.10

### Affected Resource(s)
Please list the resources as a list, for example:
- pact (provider)

Question: Is this the right place to ask if there a plan to support something like the below for authentication from the pact provider in terraform? (https://registry.terraform.io/providers/pactflow/pact/latest/docs#argument-reference)

1. username - Username for authentication. May be set via the PACT_BROKER_USERNAME environment variable.
2. password - Password for authentication. May be set via the PACT_BROKER_PASSWORD environment variable.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by mefellows** [comment]
Currently the Pact Broker doesn't have an API to set this, so the Terraform provider has no way of doing it other than to set the environment variable on the host itself. There are other Terraform modules that are better suited for that purpose, including the built in shell runners.

How are you running the pact broker now? Are you using another Terraform provider to run docker for example?

**Comment by mefellows** [comment]
@cicdenova just checking in here - are you able to elaborate on the above please? I'll close this for now, but will re-open when  you respond.
