### ISSUE TITLE
Provider cannot be instantiated - permission denied

### ISSUE THREAD

**Issue by jlsan92** [pactflow/terraform-provider-pact#8]
### Terraform Version

`v0.12.29`

### Affected Resource(s)

The provider itself

### Terraform Configuration Files
```hcl
provider "pact" {
  host         = "https://test.io"
  access_token = "testing"
  tls_insecure = true
}
```

### Debug Output
https://gist.github.com/jlsan92/9c615cce4cc74db1b75bc20ccba39b61

### Panic Output
NA

### Expected Behavior
Normal TF plan procedure

### Actual Behavior

`Error: Failed to instantiate provider "pact" to obtain schema: fork/exec /root/.terraform.d/plugins/linux_amd64/terraform-provider-pact: permission denied`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` or `terraform validate`

**Comment by mefellows** [comment]
Thanks for the report.

The error looks to be related to starting the service itself as root - do you indeed have the permission to fork/exec?

Our build is able to successfully initialise and run the plugin - see the latest release build here: https://travis-ci.org/github/pactflow/terraform/builds/711706647

Can you please provide a build that reproduces the problem? We'll be able to fix it if it indeed is an issue.

**Comment by lukaszczechowski** [comment]
Hi @jlsan92
